server:
  port: 8082  # o 8081 si el 8080 sigue en uso

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/servicios?useSSL=false&serverTimezone=UTC
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  config: 
  exception-conversion-word: "%wEx"     # Cómo mostrar excepciones (w = stack trace corto)
  file:
    name: logs/app.log                  # Ruta del archivo de log (puede ser relativo o absoluto)
    path: logs                          # Directorio de logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO                         # Nivel global de logs
    org.springframework.web: DEBUG     # Nivel para los controladores web de Spring
    org.hibernate: ERROR               # Hibernate produce mucho log, se recomienda ERROR o WARN